language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get install -y nasm kpartx
script:
  - cd src
  - make all
  - cd sdk
  - ./diskimage.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a958ef1caf3ecf95ca40
      - https://webhooks.gitter.im/e/2afe99957d977d245799
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
