OBJS:= arch/$(ARCH)/start.o  $(OBJS) arch/$(ARCH)/alloc.o arch/$(ARCH)/architecture.o \
	arch/$(ARCH)/io.o arch/$(ARCH)/vmm.o arch/$(ARCH)/switch.o arch/$(ARCH)/int.o \
	arch/$(ARCH)/idt.o arch/$(ARCH)/gdt.o arch/$(ARCH)/scheduler.o arch/$(ARCH)/cpu.o \
	arch/$(ARCH)/syscall.o arch/$(ARCH)/kbd.o arch/$(ARCH)/page.o
